export default {
  Process: "Business Process",
  "Append EndEvent": "Append End Event",
  "Append Gateway": "Append Gateway",
  "Append Task": "Append Task",
  "Append Intermediate/Boundary Event": "Append Intermediate/Boundary Event",
  "Activate the global connect tool": "Activate the Global Connect Tool",
  "Append {type}": "Append {type}",
  "Add Lane above": "Add Lane Above",
  "Divide into two Lanes": "Divide into Two Lanes",
  "Divide into three Lanes": "Divide into Three Lanes",
  "Add Lane below": "Add Lane Below",
  "Append compensation activity": "Append Compensation Activity",
  "Change type": "Change Type",
  "Connect using Association": "Connect Using Association",
  "Connect using Sequence/MessageFlow or Association": "Connect Using Sequence/MessageFlow or Association",
  "Connect using DataInputAssociation": "Connect Using DataInputAssociation",
  Remove: "Remove",
  "Activate the hand tool": "Activate the Hand Tool",
  "Activate the lasso tool": "Activate the Lasso Tool",
  "Activate the create/remove space tool": "Activate the Create/Remove Space Tool",
  "Create expanded SubProcess": "Create Expanded SubProcess",
  "Create IntermediateThrowEvent/BoundaryEvent": "Create Intermediate Throw Event/Boundary Event",
  "Create Pool/Participant": "Create Pool/Participant",
  "Parallel Multi Instance": "Parallel Multi Instance",
  "Sequential Multi Instance": "Sequential Multi Instance",
  DataObjectReference: "Data Object Reference",
  DataStoreReference: "Data Store Reference",
  Loop: "Loop",
  "Ad-hoc": "Ad-hoc",
  "Create {type}": "Create {type}",
  "Create StartEvent": "Create Start Event",
  "Create EndEvent": "Create End Event",
  "Create Task": "Create Task",
  "Create User Task": "Create User Task",
  "Create Gateway": "Create Gateway",
  "Create DataObjectReference": "Create Data Object Reference",
  "Create DataStoreReference": "Create Data Store Reference",
  "Create Group": "Create Group",
  "Create Intermediate/Boundary Event": "Create Intermediate/Boundary Event",
  "Message Start Event": "Message Start Event",
  "Timer Start Event": "Timer Start Event",
  "Conditional Start Event": "Conditional Start Event",
  "Signal Start Event": "Signal Start Event",
  "Error Start Event": "Error Start Event",
  "Escalation Start Event": "Escalation Start Event",
  "Compensation Start Event": "Compensation Start Event",
  "Message Start Event (non-interrupting)": "Message Start Event (Non-Interrupting)",
  "Timer Start Event (non-interrupting)": "Timer Start Event (Non-Interrupting)",
  "Conditional Start Event (non-interrupting)": "Conditional Start Event (Non-Interrupting)",
  "Signal Start Event (non-interrupting)": "Signal Start Event (Non-Interrupting)",
  "Escalation Start Event (non-interrupting)": "Escalation Start Event (Non-Interrupting)",
  "Message Intermediate Catch Event": "Message Intermediate Catch Event",
  "Message Intermediate Throw Event": "Message Intermediate Throw Event",
  "Timer Intermediate Catch Event": "Timer Intermediate Catch Event",
  "Escalation Intermediate Throw Event": "Escalation Intermediate Throw Event",
  "Conditional Intermediate Catch Event": "Conditional Intermediate Catch Event",
  "Link Intermediate Catch Event": "Link Intermediate Catch Event",
  "Link Intermediate Throw Event": "Link Intermediate Throw Event",
  "Compensation Intermediate Throw Event": "Compensation Intermediate Throw Event",
  "Signal Intermediate Catch Event": "Signal Intermediate Catch Event",
  "Signal Intermediate Throw Event": "Signal Intermediate Throw Event",
  "Collapsed Pool": "Collapsed Pool",
  "Expanded Pool": "Expanded Pool",
  "no parent for {element} in {parent}": "No Parent for {element} in {parent}",
  "no shape type specified": "No Shape Type Specified",
  "flow elements must be children of pools/participants": "Flow Elements Must Be Children of Pools/Participants",
  "out of bounds release": "Out of Bounds Release",
  "more than {count} child lanes": "More than {count} Child Lanes",
  "element required": "Element Required",
  "diagram not part of bpmn:Definitions": "Diagram Not Part of BPMN:Definitions",
  "no diagram to display": "No Diagram to Display",
  "no process or collaboration to display": "No Process or Collaboration to Display",
  "element {element} referenced by {referenced}#{property} not yet drawn":
    "Element {element} Referenced by {referenced}#{property} Not Yet Drawn",
  "already rendered {element}": "Already Rendered {element}",
  "failed to import {element}": "Failed to Import {element}",
  Id: "ID",
  Name: "Name",
  General: "General",
  Details: "Details",
  "Message Name": "Message Name",
  Message: "Message",
  Initiator: "Initiator",
  "Asynchronous Continuations": "Asynchronous Continuations",
  "Asynchronous Before": "Asynchronous Before",
  "Asynchronous After": "Asynchronous After",
  "Job Configuration": "Job Configuration",
  Exclusive: "Exclusive",
  "Job Priority": "Job Priority",
  "Retry Time Cycle": "Retry Time Cycle",
  Documentation: "Documentation",
  "Element Documentation": "Element Documentation",
  "History Configuration": "History Configuration",
  "History Time To Live": "History Time to Live",
  Forms: "Forms",
  "Form Key": "Form Key",
  "Form Fields": "Form Fields",
  "Business Key": "Business Key",
  "Form Field": "Form Field",
  ID: "ID",
  Type: "Type",
  Label: "Label",
  "Default Value": "Default Value",
  "Default Flow": "Default Flow",
  "Conditional Flow": "Conditional Flow",
  "Sequence Flow": "Sequence Flow",
  Validation: "Validation",
  "Add Constraint": "Add Constraint",
  Config: "Config",
  Properties: "Properties",
  "Add Property": "Add Property",
  Value: "Value",
  Listeners: "Listeners",
  "Execution Listener": "Execution Listener",
  "Event Type": "Event Type",
  "Listener Type": "Listener Type",
  "Java Class": "Java Class",
  Expression: "Expression",
  "Must provide a value": "Must Provide a Value",
  "Delegate Expression": "Delegate Expression",
  Script: "Script",
  "Script Format": "Script Format",
  "Script Type": "Script Type",
  "Inline Script": "Inline Script",
  "External Script": "External Script",
  Resource: "Resource",
  "Field Injection": "Field Injection",
  Extensions: "Extensions",
  "Input/Output": "Input/Output",
  "Input Parameters": "Input Parameters",
  "Output Parameters": "Output Parameters",
  Parameters: "Parameters",
  "Output Parameter": "Output Parameter",
  "Timer Definition Type": "Timer Definition Type",
  "Timer Definition": "Timer Definition",
  Date: "Date",
  Duration: "Duration",
  Cycle: "Cycle",
  Signal: "Signal",
  "Signal Name": "Signal Name",
  Escalation: "Escalation",
  Error: "Error",
  "Link Name": "Link Name",
  Condition: "Condition",
  "Variable Name": "Variable Name",
  "Variable Event": "Variable Event",
  "Specify more than one variable change event as a comma separated list.":
    "Specify More than One Variable Change Event as a Comma Separated List.",
  "Wait for Completion": "Wait for Completion",
  "Activity Ref": "Activity Ref",
  "Version Tag": "Version Tag",
  Executable: "Executable",
  "External Task Configuration": "External Task Configuration",
  "Task Priority": "Task Priority",
  External: "External",
  Connector: "Connector",
  "Must configure Connector": "Must Configure Connector",
  "Connector Id": "Connector ID",
  Implementation: "Implementation",
  "Field Injections": "Field Injections",
  Fields: "Fields",
  "Result Variable": "Result Variable",
  Topic: "Topic",
  "Configure Connector": "Configure Connector",
  "Input Parameter": "Input Parameter",
  Assignee: "Assignee",
  "Candidate Users": "Candidate Users",
  "Candidate Groups": "Candidate Groups",
  "Due Date": "Due Date",
  "Follow Up Date": "Follow Up Date",
  Priority: "Priority",
  "The follow up date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)":
    "The Follow Up Date as an EL Expression (e.g., ${someDate}) or an ISO Date (e.g., 2015-06-26T09:54:00)",
  "The due date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)":
    "The Due Date as an EL Expression (e.g., ${someDate}) or an ISO Date (e.g., 2015-06-26T09:54:00)",
  Variables: "Variables",
  "Candidate Starter Configuration": "Candidate Starter Configuration",
  "Candidate Starter Groups": "Candidate Starter Groups",
  "This maps to the process definition key.": "This Maps to the Process Definition Key.",
  "Candidate Starter Users": "Candidate Starter Users",
  "Specify more than one user as a comma separated list.": "Specify More than One User as a Comma Separated List.",
  "Tasklist Configuration": "Tasklist Configuration",
  Startable: "Startable",
  "Specify more than one group as a comma separated list.": "Specify More than One Group as a Comma Separated List.",
  "Execution listeners": "Execution Listeners"
};
