export default {
  Task: "Task",
  "Send Task": "Send Task",
  "Receive Task": "Receive Task",
  "User Task": "User Task",
  "Manual Task": "Manual Task",
  "Business Rule Task": "Business Rule Task",
  "Service Task": "Service Task",
  "Script Task": "Script Task",
  "Call Activity": "Call Activity",
  "Sub Process (collapsed)": "Sub Process (Collapsed)",
  "Sub Process (expanded)": "Sub Process (Expanded)",
  "Start Event": "Start Event",
  "Intermediate Throw Event": "Intermediate Throw Event",
  "End Event": "End Event",
  StartEvent: "Start Event",
  EndEvent: "End Event",
  SendTask: "Send Task",
  ReceiveTask: "Receive Task",
  UserTask: "User Task",
  ManualTask: "Manual Task",
  BusinessRuleTask: "Business Rule Task",
  ServiceTask: "Service Task",
  ScriptTask: "Script Task",
  CallActivity: "Call Activity",
  SubProcess: "Sub Process"
};
